#!/usr/bin/env python3
"""Regenerate index.md deterministically from page frontmatter + one-line summaries.

The LLM authors each page's summary (the line under the H1); this script only
assembles the catalog. meta pages are excluded. Run after any ingest or query-save.
"""

import re
from datetime import date
from pathlib import Path

from common import VAULT, SKILLS, scan_wiki, page_type, sources_list, parse

MAXSUM = 180
# Ordered keyword -> label; first match wins. Checked against the page's declared
# "**Type:** ..." line, then against tags.
TYPE_KEYWORDS = [
    ("youtube", "YouTube"), ("podcast", "Podcast"), ("repository", "Repository"),
    ("repo ", "Repository"), ("deep research", "Deep Research"), ("whitepaper", "Paper"),
    ("paper", "Paper"), ("article", "Article"), ("newsletter", "Article"),
    ("thread", "Thread"), ("transcript", "Transcript"), ("interview", "Transcript"),
    ("curriculum", "Personal"), ("cv", "Personal"), ("résumé", "Personal"),
    ("resume", "Personal"), ("profile", "Personal"), ("journal", "Personal"),
    ("prd", "Project"), ("requirements", "Project"), ("specification", "Project"),
    ("spec", "Project"), ("brief", "Project"), ("pitch", "Project"), ("playbook", "Project"),
    ("blueprint", "Project"), ("template", "Template"),
]
SRC_TYPE_BY_TAG = [
    ("repository", "Repository"), ("youtube", "YouTube"), ("podcast", "Podcast"),
    ("paper", "Paper"), ("article", "Article"), ("thread", "Thread"),
    ("transcript", "Transcript"), ("template", "Template"),
    ("deep-research", "Deep Research"), ("research", "Deep Research"),
    ("personal", "Personal"), ("project", "Project"),
]
TYPE_DECL_RE = re.compile(r"(?im)^\*\*Type:\*\*\s*(.+)$")


def cell(text: str) -> str:
    text = re.sub(r"\s+", " ", (text or "").strip()).replace("|", "/")
    return text[:MAXSUM - 1] + "…" if len(text) > MAXSUM else text


def datestr(fm: dict) -> str:
    return str(fm.get("updated") or fm.get("created") or "")


def src_type(fm: dict, body: str, slug: str = "") -> str:
    m = TYPE_DECL_RE.search(body or "")
    declared = m.group(1).lower() if m else ""
    if declared:
        for kw, label in TYPE_KEYWORDS:
            if kw in declared:
                return label
    tags = [str(t).lower() for t in (fm.get("tags") or [])]
    for tag, label in SRC_TYPE_BY_TAG:
        if tag in tags:
            return label
    if "--" in slug:  # repo distillations are named source-<org>--<repo>
        return "Repository"
    return "Source"


def collect(pages):
    by = {t: [] for t in ["source", "entity", "concept", "project",
                          "domain", "comparison", "synthesis", "query"]}
    for slug, info in pages.items():
        t = page_type(info)
        if t in by:
            by[t].append((slug, info["parsed"]["frontmatter"] or {},
                          info["parsed"]["summary"], info["parsed"]["body"]))
    return by


def skills_rows():
    rows = []
    sk = VAULT / "skills"
    if not sk.exists():
        return rows
    for d in sorted(p for p in sk.iterdir() if p.is_dir()):
        sf = d / "SKILL.md"
        if not sf.exists():
            continue
        fm = parse(sf)["frontmatter"] or {}
        desc = (fm.get("description") or "").strip()
        if not desc:
            continue  # shared-asset dirs etc. are not catalogued skills
        rows.append((fm.get("name", d.name), cell(desc), "active"))
    return rows


def table(header, rows):
    sep = "|" + "|".join(["---"] * len(header.split("|")[1:-1])) + "|"
    return "\n".join([header, sep] + rows)


def build():
    pages = scan_wiki()
    by = collect(pages)
    content = sum(len(v) for v in by.values())
    today = str(date.today())

    out = ["# Wiki Index", "",
           f"> Last updated: {today} | Total pages: {content} | Total sources: {len(by['source'])}",
           "", "> Auto-generated by `skills/second-brain/scripts/build_index.py` — do not hand-edit tables.", ""]

    # Sources (by date)
    out += ["## Sources", ""]
    rows = [f"| [[{s}]] | {cell(summ)} | {datestr(fm)} | {src_type(fm, body, s)} |"
            for s, fm, summ, body in sorted(by["source"], key=lambda x: datestr(x[1]))]
    out += [table("| Page | Summary | Date | Source Type |", rows), ""]

    # Entities / Concepts / Domains (alpha)
    for sec, key in [("Entities", "entity"), ("Concepts", "concept"), ("Domains", "domain")]:
        out += [f"## {sec}", ""]
        rows = [f"| [[{s}]] | {cell(summ)} | {len(sources_list(fm))} | {fm.get('confidence','')} |"
                for s, fm, summ, body in sorted(by[key], key=lambda x: x[0])]
        out += [table("| Page | Summary | Sources | Confidence |", rows), ""]

    # Projects (alpha)
    out += ["## Projects", ""]
    rows = [f"| [[{s}]] | {cell(summ)} | {cell(str(fm.get('status','')))} | {len(sources_list(fm))} |"
            for s, fm, summ, body in sorted(by["project"], key=lambda x: x[0])]
    out += [table("| Page | Summary | Status | Sources |", rows), ""]

    # Comparisons (alpha)
    out += ["## Comparisons", ""]
    rows = [f"| [[{s}]] | {cell(summ)} | {datestr(fm)} |"
            for s, fm, summ, body in sorted(by["comparison"], key=lambda x: x[0])]
    out += [table("| Page | Summary | Date |", rows), ""]

    # Syntheses (by date, list sources)
    out += ["## Syntheses", ""]
    rows = []
    for s, fm, summ, body in sorted(by["synthesis"], key=lambda x: datestr(x[1])):
        srcs = ", ".join(str(x) for x in sources_list(fm)) or "—"
        rows.append(f"| [[{s}]] | {cell(summ)} | {datestr(fm)} | {cell(srcs)} |")
    out += [table("| Page | Summary | Date | Sources |", rows), ""]

    # Queries (by date)
    out += ["## Queries", ""]
    rows = [f"| [[{s}]] | {cell(summ)} | {datestr(fm)} |"
            for s, fm, summ, body in sorted(by["query"], key=lambda x: datestr(x[1]))]
    out += [table("| Page | Summary | Date |", rows), ""]

    # Skills
    out += ["## Skills", ""]
    rows = [f"| {n} | {d} | {st} |" for n, d, st in skills_rows()]
    out += [table("| Skill | Summary | Status |", rows), ""]

    (VAULT / "index.md").write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
    print(f"index.md regenerated: {content} content pages, {len(by['source'])} sources, "
          f"{len(skills_rows())} skills.")


if __name__ == "__main__":
    build()
