#!/usr/bin/env bash
# repo-capture.sh — Capture GitHub repository provenance metadata
# Usage: bash skills/wiki-maintenance/scripts/repo-capture.sh <org> <repo>
# Output: raw/repos/<org>--<repo>/_capture.yml
#
# Requires: gh CLI (https://cli.github.com) for full metadata.
# Falls back to stub values if gh is unavailable so the ingest can proceed.

set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <org> <repo>" >&2
  exit 1
fi

ORG="$1"
REPO="$2"
SLUG="${ORG}--${REPO}"
OUTDIR="raw/repos/${SLUG}"
OUT="${OUTDIR}/_capture.yml"

mkdir -p "$OUTDIR"

SHA="unknown"
STARS=0
LICENSE="unknown"
DESCRIPTION=""
DEFAULT_BRANCH="main"
SNAPSHOT=$(date +%Y-%m-%d)

if command -v gh &>/dev/null; then
  echo "  gh CLI found — fetching live metadata for ${ORG}/${REPO}..."

  SHA=$(gh api "repos/${ORG}/${REPO}/commits/HEAD" \
    --jq '.sha' 2>/dev/null | head -c 12) || SHA="unknown"

  REPO_JSON=$(gh repo view "${ORG}/${REPO}" \
    --json stargazerCount,licenseInfo,description,defaultBranchRef 2>/dev/null) || REPO_JSON="{}"

  STARS=$(echo "$REPO_JSON" | python3 -c \
    "import sys,json; d=json.load(sys.stdin); print(d.get('stargazerCount',0))" 2>/dev/null) || STARS=0

  LICENSE=$(echo "$REPO_JSON" | python3 -c \
    "import sys,json; d=json.load(sys.stdin); l=d.get('licenseInfo'); print(l['name'] if l else 'unknown')" 2>/dev/null) || LICENSE="unknown"

  DESCRIPTION=$(echo "$REPO_JSON" | python3 -c \
    "import sys,json; d=json.load(sys.stdin); print(d.get('description','') or '')" 2>/dev/null) || DESCRIPTION=""

  DEFAULT_BRANCH=$(echo "$REPO_JSON" | python3 -c \
    "import sys,json; d=json.load(sys.stdin); b=d.get('defaultBranchRef'); print(b['name'] if b else 'main')" 2>/dev/null) || DEFAULT_BRANCH="main"

  echo "  Captured: commit=${SHA}, stars=${STARS}, license=${LICENSE}"
else
  echo "  Warning: gh CLI not found. Writing stub _capture.yml — fill in manually or install gh." >&2
fi

cat > "$OUT" <<EOF
# Repository provenance — auto-generated by repo-capture.sh
# Do not hand-edit; re-run repo-capture.sh to refresh.
repo: ${REPO}
org: ${ORG}
slug: ${SLUG}
url: https://github.com/${ORG}/${REPO}
description: "${DESCRIPTION}"
commit: ${SHA}
default_branch: ${DEFAULT_BRANCH}
stars: ${STARS}
license: ${LICENSE}
snapshot: ${SNAPSHOT}
EOF

echo "  Wrote ${OUT}"
